
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ESTADO FECHA PALABRA SEXOentrada : PALABRA PALABRA PALABRA FECHA SEXO ESTADO'
    
_lr_action_items = {'PALABRA':([0,2,3,],[2,3,4,]),'$end':([1,7,],[0,-1,]),'FECHA':([4,],[5,]),'SEXO':([5,],[6,]),'ESTADO':([6,],[7,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'entrada':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> entrada","S'",1,None,None,None),
  ('entrada -> PALABRA PALABRA PALABRA FECHA SEXO ESTADO','entrada',6,'p_input','parser.py',9),
]
